[package]
name = "three-card-poker"
version = "0.1.0"
edition = "2024"

[profile.test]
opt-level = 1

[profile.release]
opt-level = 3

[dependencies]
rayon = "1.11.0"
rand = "0.9.2"
plotters = "0.3.7"
itertools = "0.14.0"